Repository softwareconstruction240/softwareconstruction, pull requests merged in 2025-01, with the labels that each got.

#225 Update instructions to clone from chess template from beginning
  chess/0-chess-moves/chess-moves.md
  chess/0-chess-moves/creating-chess-github-repo-transcript.txt
  chess/0-chess-moves/getting-started.md
  chess/0-chess-moves/starter-code/chess.zip
  chess/chess-github-repository/chess-github-repository.md
  chess/chess-github-repository/create-repo.png
  chess/chess-github-repository/use-template.png
  chess/chess.md
  instruction/programming-exam/programming-exam.md
Labels: documentation, enhancement

#223 Introduce Git Commit Workflow
  instruction/git/GitCommitWorkflow.png
  instruction/git/git.md
Labels: documentation

#231 Update getting-started.md Fix typo in file path
  chess/1-chess-game/getting-started.md
Labels: bug

#230 Correct castling rules in chess-game.md
  chess/1-chess-game/chess-game.md
Labels: enhancement

#239 Update chess-game.md Adjust formatting...
  chess/0-chess-moves/chess-moves.md
  chess/1-chess-game/chess-game.md
Labels: documentation
